package com.romeiro.picklejar.model;

public enum LogType {
    PASSWORD_ACCESS, PASSWORD_EDITING, ACCOUNT_LOGIN, ACCOUNT_LOGOUT,
    PASSWORD_DELETE, PASSWORD_COPY, PASSWORD_URL_ACCESS, ACCOUNT_ACCESS
}
